import type { Config } from "tailwindcss"

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
    "*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
        slate: {
          50: "#f8fafc",
          100: "#f1f5f9",
          200: "#e2e8f0",
          300: "#cbd5e1",
          400: "#94a3b8",
          500: "#64748b",
          600: "#475569",
          700: "#334155",
          800: "#1e293b",
          900: "#0f172a",
          950: "#020617",
        },
        // Stitch MD3 Palette
        "on-surface-variant": "#3f4943",
        "on-tertiary": "#ffffff",
        "primary-container": "#006c49",
        "on-secondary": "#ffffff",
        "surface-container-high": "#dce9ff",
        "on-surface": "#0b1c30",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#b4c5ff",
        "tertiary": "#3d4947",
        "on-tertiary-container": "#cedbd9",
        "surface-tint": "#006c49",
        "surface-container-lowest": "#ffffff",
        "outline": "#6f7a72",
        "surface-container-low": "#eff4ff",
        "inverse-surface": "#213145",
        "secondary-fixed": "#dbe1ff",
        "surface-variant": "#d3e4fe",
        "on-secondary-container": "#fefcff",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#00174b",
        "on-primary-fixed-variant": "#005236",
        "secondary-container": "#316bf3",
        "on-secondary-fixed-variant": "#003ea8",
        "error-container": "#ffdad6",
        "surface": "#f8f9ff",
        "on-error": "#ffffff",
        "primary-fixed": "#9df4c8",
        "tertiary-fixed": "#d7e5e2",
        "tertiary-container": "#54615f",
        "on-primary-container": "#93eabe",
        "on-tertiary-fixed-variant": "#3d4947",
        "surface-dim": "#cbdbf5",
        "surface-bright": "#f8f9ff",
        "on-background": "#0b1c30",
        "surface-container": "#e5eeff",
        "surface-container-highest": "#d3e4fe",
        "on-tertiary-fixed": "#121e1c",
        "tertiary-fixed-dim": "#bcc9c7",
        "inverse-on-surface": "#eaf1ff",
        "on-primary-fixed": "#002113",
        "inverse-primary": "#81d8ad",
        "outline-variant": "#bec9c0",
        "primary-fixed-dim": "#81d8ad",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      spacing: {
        "gutter": "24px",
        "base": "8px",
        "sm": "12px",
        "margin-mobile": "16px",
        "xs": "4px",
        "margin-desktop": "48px",
        "md": "24px",
        "xl": "80px",
        "lg": "48px"
      },
      fontFamily: {
        "headline-lg": ["Geist", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "14px", "fontWeight": "500" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }]
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}

export default config
